### PR TITLE
DiffOf implementation

### PR DESCRIPTION
**Pull request by anikeevda**
As a solution for #1 I propose this but I am not sure this quite elegant

### CODE REVIEW

**Comment by stepanets** [comment]
Can you implement `ByKeys` way? I think you should  test `ByValues` in `ByValuesTest` and `DiffOf` should be tested with some  stub or mock implementation of `DiffWay`. And use import function please.

**Comment by anikeevda** [comment]
> 
> 
> Can you implement `ByKeys` way? I think you should test `ByValues` in `ByValuesTest` and `DiffOf` should be tested with some stub or mock implementation of `DiffWay`. And use import function please.

Well that woud be `ByValuesAndIndexes` for semantical reason

**Comment by stepanets** [comment]
I ment `ByKeys ` that uses `array_diff_key`. You implemented `array_diff_assoc`, but thats ok. The only thing I worry about is using `index` word. `Index` usualy means integer value while `key` can be any.

**Comment by anikeevda** [comment]
> 
> 
> I ment `ByKeys ` that uses `array_diff_key`. You implemented `array_diff_assoc`, but thats ok. The only thing I worry about is using `index` word. `Index` usualy means integer value while `key` can be any.

I agree about `Keys` instead of `Indexes`. Also I think we should do something with code below in every classes, possibly decorate it.

`
...(new Mapped(
            $this->arrayees,
            static function (Arrayee $arrayee) {
                return $arrayee->asArray();
            }
        ))->asArray()
`

And I propose to discuss possibility adding class description which standard library function decorated in it.

**Review by stepanets — APPROVED** [review]

**Comment by stepanets** [comment]
> I agree about `Keys` instead of `Indexes`. Also I think we should do something with code below in every classes, possibly decorate it.
> 
> `...(new Mapped( $this->arrayees, static function (Arrayee $arrayee) { return $arrayee->asArray(); } ))->asArray()`
> 
> And I propose to discuss possibility adding class description which standard library function decorated in it.

Can you open new ticket about this?

**Pull request merged**
